/* This SAS program was automatically generated by Stat/Transfer */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\test\w1\w1_j_mtc_lv6.2.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\test\w1\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = w1_j_mtc ;

proc format library = library ;
   value W1MTC0A /* w1:任教的主要科目 */
      1 = '國文'  
      2 = '英文'  
      3 = '數學'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC0B /* w1:主/副修/任教主要科目? */
      1 = '是'  
      2 = '否'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC0C /* w1:該科?幾年? */
      1 = '不到1年'  
      2 = '不到3年'  
      3 = '不到6年'  
      4 = '不到9年'  
      5 = '不到20年'  
      6 = '20年以上(含)'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC0D /* w1:每週/這班/上課時數? */
      1 = '1~3小時'  
      2 = '4~6小時'  
      3 = '7~9小時'  
      4 = '10小時以上(含)'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC0E /* w1:任教科目/這班程度？ */
      1 = '特別好'  
      2 = '比較好'  
      3 = '差不多'  
      4 = '比較差'  
      5 = '特別差'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC0F /* w1:任教科目/分組教學？ */
      1 = '有'  
      2 = '沒有'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC0G /* w1:教學法/輸入式 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC0H /* w1:教學法/探索或啟發式 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC0I /* w1:教材/教科書 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC1A /* w1:教材/課外參考書 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC1B /* w1:教材/自行編寫或設計 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC1C /* w1:教材/其他 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC1D /* w1:輔助教具/視聽或電腦設備 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC1E /* w1:輔助教具/掛圖/布偶/遊戲/益智玩具 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC1F /* w1:輔助教具/戶外教學或參觀 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC1G /* w1:上課/維持秩序 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC1H /* w1:上課/測驗或考試 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC18A /* w1:這班一週考幾次試？ */
      1 = '0次'  
      2 = '1~2次'  
      3 = '3~4次'  
      4 = '5次以上(含)'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC19A /* w1:每週/幾次作業？ */
      1 = '0次'  
      2 = '1次'  
      3 = '2次'  
      4 = '3次以上(含)'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC2A /* w1:做完指定作業時間？ */
      1 = '不到1小時'  
      2 = '1~2小時(不含2小時)'  
      3 = '2到3小時(不含3小時)'  
      4 = '3到4小時(不含4小時)'  
      5 = '4小時以上'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC21A /* w1:作業/課本內習題 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC2B /* w1:作業/參考書練習題 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC2C /* w1:作業/課外讀物 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC2D /* w1:作業/作文練習 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC2E /* w1:作業/簡報、收集資料、寫心得 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC2F /* w1:作業措施/公佈成績 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC2G /* w1:作業措施/檢討答案 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC2H /* w1:作業措施/獎賞表現好的 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC2I /* w1:作業措施/處罰表現差的 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC3A /* w1:作業措施/個別輔導 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC3B /* w1:作業措施/通知家長 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC3C /* w1:要求閱讀/心得報告? */
      1 = '沒有'  
      2 = '1本'  
      3 = '2本'  
      4 = '3本'  
      5 = '4本以上(含)'  
      6 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC3D /* w1:評量優先順序/考試成績? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC3E /* w1:評量優先順序/作業成績? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC3F /* w1:評量優先順序/上課表現? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC3G /* w1:評量優先順序/學習態度? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1MTC3H /* w1:評量優先順序/進步情況? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;

DATA library.&dataset ;
INFILE datafile LRECL=101;
INPUT
   STUD_ID  1-5             W1STWT1  6-24            W1MTC01  25           
   W1MTC02  26-27           W1MTC03  28-29           W1MTC04  30-31        
   W1MTC05  32-33           W1MTC06  34-35           W1MTC07  36-37        
   W1MTC08  38-39           W1MTC09  40-41           W1MTC10  42-43        
   W1MTC11  44-45           W1MTC12  46-47           W1MTC13  48-49        
   W1MTC14  50-51           W1MTC15  52-53           W1MTC16  54-55        
   W1MTC17  56-57           W1MTC18A  58-59          W1MTC19A  60-61       
   W1MTC20  62-63           W1MTC21A  64-65          W1MTC22  66-67        
   W1MTC23  68-69           W1MTC24  70-71           W1MTC25  72-73        
   W1MTC26  74-75           W1MTC27  76-77           W1MTC28  78-79        
   W1MTC29  80-81           W1MTC30  82-83           W1MTC31  84-85        
   W1MTC32  86-87           W1MTC33  88-89           W1MTC34  90-91        
   W1MTC35  92-93           W1MTC36  94-95           W1MTC37  96-97        
   W1SUMERR  98             W1SUMMIS  99-100         W1SUMTRP  101         
 ;                       

LABEL
   STUD_ID = "學生代碼"
   W1STWT1 = "w1:學生樣本權數(標準化過後)"
   W1MTC01 = "w1:任教的主要科目"
   W1MTC02 = "w1:主/副修/任教主要科目?"
   W1MTC03 = "w1:該科?幾年?"
   W1MTC04 = "w1:每週/這班/上課時數?"
   W1MTC05 = "w1:任教科目/這班程度？"
   W1MTC06 = "w1:任教科目/分組教學？"
   W1MTC07 = "w1:教學法/輸入式"
   W1MTC08 = "w1:教學法/探索或啟發式"
   W1MTC09 = "w1:教材/教科書"
   W1MTC10 = "w1:教材/課外參考書"
   W1MTC11 = "w1:教材/自行編寫或設計"
   W1MTC12 = "w1:教材/其他"
   W1MTC13 = "w1:輔助教具/視聽或電腦設備"
   W1MTC14 = "w1:輔助教具/掛圖/布偶/遊戲/益智玩具"
   W1MTC15 = "w1:輔助教具/戶外教學或參觀"
   W1MTC16 = "w1:上課/維持秩序"
   W1MTC17 = "w1:上課/測驗或考試"
   W1MTC18A = "w1:這班一週考幾次試？"
   W1MTC19A = "w1:每週/幾次作業？"
   W1MTC20 = "w1:做完指定作業時間？"
   W1MTC21A = "w1:作業/課本內習題"
   W1MTC22 = "w1:作業/參考書練習題"
   W1MTC23 = "w1:作業/課外讀物"
   W1MTC24 = "w1:作業/作文練習"
   W1MTC25 = "w1:作業/簡報、收集資料、寫心得"
   W1MTC26 = "w1:作業措施/公佈成績"
   W1MTC27 = "w1:作業措施/檢討答案"
   W1MTC28 = "w1:作業措施/獎賞表現好的"
   W1MTC29 = "w1:作業措施/處罰表現差的"
   W1MTC30 = "w1:作業措施/個別輔導"
   W1MTC31 = "w1:作業措施/通知家長"
   W1MTC32 = "w1:要求閱讀/心得報告?"
   W1MTC33 = "w1:評量優先順序/考試成績?"
   W1MTC34 = "w1:評量優先順序/作業成績?"
   W1MTC35 = "w1:評量優先順序/上課表現?"
   W1MTC36 = "w1:評量優先順序/學習態度?"
   W1MTC37 = "w1:評量優先順序/進步情況?"
   W1SUMERR = "w1:不合理值總和"
   W1SUMMIS = "w1:未填答總和"
   W1SUMTRP = "w1:劃記答案卡不應作答部分" ;

FORMAT
   W1MTC01 W1MTC0A.         W1MTC02 W1MTC0B.         W1MTC03 W1MTC0C.      
   W1MTC04 W1MTC0D.         W1MTC05 W1MTC0E.         W1MTC06 W1MTC0F.      
   W1MTC07 W1MTC0G.         W1MTC08 W1MTC0H.         W1MTC09 W1MTC0I.      
   W1MTC10 W1MTC1A.         W1MTC11 W1MTC1B.         W1MTC12 W1MTC1C.      
   W1MTC13 W1MTC1D.         W1MTC14 W1MTC1E.         W1MTC15 W1MTC1F.      
   W1MTC16 W1MTC1G.         W1MTC17 W1MTC1H.         W1MTC18A W1MTC18A.    
   W1MTC19A W1MTC19A.       W1MTC20 W1MTC2A.         W1MTC21A W1MTC21A.    
   W1MTC22 W1MTC2B.         W1MTC23 W1MTC2C.         W1MTC24 W1MTC2D.      
   W1MTC25 W1MTC2E.         W1MTC26 W1MTC2F.         W1MTC27 W1MTC2G.      
   W1MTC28 W1MTC2H.         W1MTC29 W1MTC2I.         W1MTC30 W1MTC3A.      
   W1MTC31 W1MTC3B.         W1MTC32 W1MTC3C.         W1MTC33 W1MTC3D.      
   W1MTC34 W1MTC3E.         W1MTC35 W1MTC3F.         W1MTC36 W1MTC3G.      
   W1MTC37 W1MTC3H.       ;
                     

LENGTH
   STUD_ID 4                W1MTC01 3                W1MTC02 3             
   W1MTC03 3                W1MTC04 3                W1MTC05 3             
   W1MTC06 3                W1MTC07 3                W1MTC08 3             
   W1MTC09 3                W1MTC10 3                W1MTC11 3             
   W1MTC12 3                W1MTC13 3                W1MTC14 3             
   W1MTC15 3                W1MTC16 3                W1MTC17 3             
   W1MTC18A 3               W1MTC19A 3               W1MTC20 3             
   W1MTC21A 3               W1MTC22 3                W1MTC23 3             
   W1MTC24 3                W1MTC25 3                W1MTC26 3             
   W1MTC27 3                W1MTC28 3                W1MTC29 3             
   W1MTC30 3                W1MTC31 3                W1MTC32 3             
   W1MTC33 3                W1MTC34 3                W1MTC35 3             
   W1MTC36 3                W1MTC37 3                W1SUMERR 3            
   W1SUMMIS 3               W1SUMTRP 3 ;

      

RUN ;
