/* This SAS program was automatically generated by Stat/Transfer */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\test\w1\w1_j_etc_lv6.2.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\test\w1\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = w1_j_etc ;

proc format library = library ;
   value W1ETC0A /* w1:任教的主要科目 */
      1 = '國文'  
      2 = '英文'  
      3 = '數學'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC0B /* w1:主/副修/任教主要科目? */
      1 = '是'  
      2 = '否'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC0C /* w1:該科?幾年? */
      1 = '不到1年'  
      2 = '不到3年'  
      3 = '不到6年'  
      4 = '不到9年'  
      5 = '不到20年'  
      6 = '20年以上(含)'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC0D /* w1:每週/這班/上課時數? */
      1 = '1~3小時'  
      2 = '4~6小時'  
      3 = '7~9小時'  
      4 = '10小時以上(含)'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC0E /* w1:任教科目/這班程度？ */
      1 = '特別好'  
      2 = '比較好'  
      3 = '差不多'  
      4 = '比較差'  
      5 = '特別差'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC0F /* w1:任教科目/分組教學？ */
      1 = '有'  
      2 = '沒有'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC0G /* w1:教學法/輸入式 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC0H /* w1:教學法/探索或啟發式 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC0I /* w1:教材/教科書 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC1A /* w1:教材/課外參考書 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC1B /* w1:教材/自行編寫或設計 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC1C /* w1:教材/其他 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC1D /* w1:輔助教具/視聽或電腦設備 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC1E /* w1:輔助教具/掛圖/布偶/遊戲/益智玩具 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC1F /* w1:輔助教具/戶外教學或參觀 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC1G /* w1:上課/維持秩序 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC1H /* w1:上課/測驗或考試 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC18A /* w1:這班一週考幾次試？ */
      1 = '0次'  
      2 = '1~2次'  
      3 = '3~4次'  
      4 = '5次以上(含)'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC19A /* w1:每週/幾次作業？ */
      1 = '0次'  
      2 = '1次'  
      3 = '2次'  
      4 = '3次以上(含)'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC2A /* w1:做完指定作業時間？ */
      1 = '不到1小時'  
      2 = '1~2小時(不含2小時)'  
      3 = '2到3小時(不含3小時)'  
      4 = '3到4小時(不含4小時)'  
      5 = '4小時以上'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC21A /* w1:作業/課本內習題 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC2B /* w1:作業/參考書練習題 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC2C /* w1:作業/課外讀物 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC2D /* w1:作業/作文練習 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC2E /* w1:作業/簡報、收集資料、寫心得 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC2F /* w1:作業措施/公佈成績 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC2G /* w1:作業措施/檢討答案 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC2H /* w1:作業措施/獎賞表現好的 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC2I /* w1:作業措施/處罰表現差的 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC3A /* w1:作業措施/個別輔導 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC3B /* w1:作業措施/通知家長 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC3C /* w1:要求閱讀/心得報告? */
      1 = '沒有'  
      2 = '1本'  
      3 = '2本'  
      4 = '3本'  
      5 = '4本以上(含)'  
      6 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC3D /* w1:評量優先順序/考試成績? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC3E /* w1:評量優先順序/作業成績? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC3F /* w1:評量優先順序/上課表現? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC3G /* w1:評量優先順序/學習態度? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1ETC3H /* w1:評量優先順序/進步情況? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;

DATA library.&dataset ;
INFILE datafile LRECL=95;
INPUT
   STUD_ID  1-5             W1STWT1  6-24            W1ETC01  25           
   W1ETC02  26-27           W1ETC03  28-29           W1ETC04  30-31        
   W1ETC05  32-33           W1ETC06  34-35           W1ETC07  36           
   W1ETC08  37-38           W1ETC09  39-40           W1ETC10  41-42        
   W1ETC11  43-44           W1ETC12  45-46           W1ETC13  47-48        
   W1ETC14  49-50           W1ETC15  51-52           W1ETC16  53-54        
   W1ETC17  55              W1ETC18A  56-57          W1ETC19A  58          
   W1ETC20  59-60           W1ETC21A  61             W1ETC22  62-63        
   W1ETC23  64-65           W1ETC24  66-67           W1ETC25  68-69        
   W1ETC26  70-71           W1ETC27  72              W1ETC28  73-74        
   W1ETC29  75-76           W1ETC30  77-78           W1ETC31  79-80        
   W1ETC32  81-82           W1ETC33  83-84           W1ETC34  85-86        
   W1ETC35  87-88           W1ETC36  89-90           W1ETC37  91-92        
   W1SUMERR  93             W1SUMMIS  94             W1SUMTRP  95          
 ;                       

LABEL
   STUD_ID = "學生代碼"
   W1STWT1 = "w1:學生樣本權數(標準化過後)"
   W1ETC01 = "w1:任教的主要科目"
   W1ETC02 = "w1:主/副修/任教主要科目?"
   W1ETC03 = "w1:該科?幾年?"
   W1ETC04 = "w1:每週/這班/上課時數?"
   W1ETC05 = "w1:任教科目/這班程度？"
   W1ETC06 = "w1:任教科目/分組教學？"
   W1ETC07 = "w1:教學法/輸入式"
   W1ETC08 = "w1:教學法/探索或啟發式"
   W1ETC09 = "w1:教材/教科書"
   W1ETC10 = "w1:教材/課外參考書"
   W1ETC11 = "w1:教材/自行編寫或設計"
   W1ETC12 = "w1:教材/其他"
   W1ETC13 = "w1:輔助教具/視聽或電腦設備"
   W1ETC14 = "w1:輔助教具/掛圖/布偶/遊戲/益智玩具"
   W1ETC15 = "w1:輔助教具/戶外教學或參觀"
   W1ETC16 = "w1:上課/維持秩序"
   W1ETC17 = "w1:上課/測驗或考試"
   W1ETC18A = "w1:這班一週考幾次試？"
   W1ETC19A = "w1:每週/幾次作業？"
   W1ETC20 = "w1:做完指定作業時間？"
   W1ETC21A = "w1:作業/課本內習題"
   W1ETC22 = "w1:作業/參考書練習題"
   W1ETC23 = "w1:作業/課外讀物"
   W1ETC24 = "w1:作業/作文練習"
   W1ETC25 = "w1:作業/簡報、收集資料、寫心得"
   W1ETC26 = "w1:作業措施/公佈成績"
   W1ETC27 = "w1:作業措施/檢討答案"
   W1ETC28 = "w1:作業措施/獎賞表現好的"
   W1ETC29 = "w1:作業措施/處罰表現差的"
   W1ETC30 = "w1:作業措施/個別輔導"
   W1ETC31 = "w1:作業措施/通知家長"
   W1ETC32 = "w1:要求閱讀/心得報告?"
   W1ETC33 = "w1:評量優先順序/考試成績?"
   W1ETC34 = "w1:評量優先順序/作業成績?"
   W1ETC35 = "w1:評量優先順序/上課表現?"
   W1ETC36 = "w1:評量優先順序/學習態度?"
   W1ETC37 = "w1:評量優先順序/進步情況?"
   W1SUMERR = "w1:不合理值總和"
   W1SUMMIS = "w1:未填答總和"
   W1SUMTRP = "w1:劃記答案卡不應作答部分" ;

FORMAT
   W1ETC01 W1ETC0A.         W1ETC02 W1ETC0B.         W1ETC03 W1ETC0C.      
   W1ETC04 W1ETC0D.         W1ETC05 W1ETC0E.         W1ETC06 W1ETC0F.      
   W1ETC07 W1ETC0G.         W1ETC08 W1ETC0H.         W1ETC09 W1ETC0I.      
   W1ETC10 W1ETC1A.         W1ETC11 W1ETC1B.         W1ETC12 W1ETC1C.      
   W1ETC13 W1ETC1D.         W1ETC14 W1ETC1E.         W1ETC15 W1ETC1F.      
   W1ETC16 W1ETC1G.         W1ETC17 W1ETC1H.         W1ETC18A W1ETC18A.    
   W1ETC19A W1ETC19A.       W1ETC20 W1ETC2A.         W1ETC21A W1ETC21A.    
   W1ETC22 W1ETC2B.         W1ETC23 W1ETC2C.         W1ETC24 W1ETC2D.      
   W1ETC25 W1ETC2E.         W1ETC26 W1ETC2F.         W1ETC27 W1ETC2G.      
   W1ETC28 W1ETC2H.         W1ETC29 W1ETC2I.         W1ETC30 W1ETC3A.      
   W1ETC31 W1ETC3B.         W1ETC32 W1ETC3C.         W1ETC33 W1ETC3D.      
   W1ETC34 W1ETC3E.         W1ETC35 W1ETC3F.         W1ETC36 W1ETC3G.      
   W1ETC37 W1ETC3H.       ;
                     

LENGTH
   STUD_ID 4                W1ETC01 3                W1ETC02 3             
   W1ETC03 3                W1ETC04 3                W1ETC05 3             
   W1ETC06 3                W1ETC07 3                W1ETC08 3             
   W1ETC09 3                W1ETC10 3                W1ETC11 3             
   W1ETC12 3                W1ETC13 3                W1ETC14 3             
   W1ETC15 3                W1ETC16 3                W1ETC17 3             
   W1ETC18A 3               W1ETC19A 3               W1ETC20 3             
   W1ETC21A 3               W1ETC22 3                W1ETC23 3             
   W1ETC24 3                W1ETC25 3                W1ETC26 3             
   W1ETC27 3                W1ETC28 3                W1ETC29 3             
   W1ETC30 3                W1ETC31 3                W1ETC32 3             
   W1ETC33 3                W1ETC34 3                W1ETC35 3             
   W1ETC36 3                W1ETC37 3                W1SUMERR 3            
   W1SUMMIS 3               W1SUMTRP 3 ;

      

RUN ;
