/* This SAS program was automatically generated by Stat/Transfer */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\test\w1\w1_j_ctc_lv6.2.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\test\w1\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = w1_j_ctc ;

proc format library = library ;
   value W1CTC0A /* w1:任教的主要科目 */
      1 = '國文'  
      2 = '英文'  
      3 = '數學'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC0B /* w1:主/副修/任教主要科目? */
      1 = '是'  
      2 = '否'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC0C /* w1:該科?幾年? */
      1 = '不到1年'  
      2 = '不到3年'  
      3 = '不到6年'  
      4 = '不到9年'  
      5 = '不到20年'  
      6 = '20年以上(含)'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC0D /* w1:每週/這班/上課時數? */
      1 = '1~3小時'  
      2 = '4~6小時'  
      3 = '7~9小時'  
      4 = '10小時以上(含)'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC0E /* w1:任教科目/這班程度？ */
      1 = '特別好'  
      2 = '比較好'  
      3 = '差不多'  
      4 = '比較差'  
      5 = '特別差'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC0F /* w1:任教科目/分組教學？ */
      1 = '有'  
      2 = '沒有'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC0G /* w1:教學法/輸入式 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC0H /* w1:教學法/探索或啟發式 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC0I /* w1:教材/教科書 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC1A /* w1:教材/課外參考書 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC1B /* w1:教材/自行編寫或設計 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC1C /* w1:教材/其他 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC1D /* w1:輔助教具/視聽或電腦設備 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC1E /* w1:輔助教具/掛圖/布偶/遊戲/益智玩具 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC1F /* w1:輔助教具/戶外教學或參觀 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC1G /* w1:上課/維持秩序 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC1H /* w1:上課/測驗或考試 */
      1 = '經常'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC18A /* w1:這班一週考幾次試？ */
      1 = '0次'  
      2 = '1~2次'  
      3 = '3~4次'  
      4 = '5次以上(含)'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC19A /* w1:每週/幾次作業？ */
      1 = '0次'  
      2 = '1次'  
      3 = '2次'  
      4 = '3次以上(含)'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC2A /* w1:做完指定作業時間？ */
      1 = '不到1小時'  
      2 = '1~2小時(不含2小時)'  
      3 = '2到3小時(不含3小時)'  
      4 = '3到4小時(不含4小時)'  
      5 = '4小時以上'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC21A /* w1:作業/課本內習題 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC2B /* w1:作業/參考書練習題 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC2C /* w1:作業/課外讀物 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC2D /* w1:作業/作文練習 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC2E /* w1:作業/簡報、收集資料、寫心得 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC2F /* w1:作業措施/公佈成績 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC2G /* w1:作業措施/檢討答案 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC2H /* w1:作業措施/獎賞表現好的 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC2I /* w1:作業措施/處罰表現差的 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC3A /* w1:作業措施/個別輔導 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC3B /* w1:作業措施/通知家長 */
      1 = '一定有'  
      2 = '有時'  
      3 = '偶爾'  
      4 = '從不'  
      5 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC3C /* w1:要求閱讀/心得報告? */
      1 = '沒有'  
      2 = '1本'  
      3 = '2本'  
      4 = '3本'  
      5 = '4本以上(含)'  
      6 = '不適用'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC3D /* w1:評量優先順序/考試成績? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC3E /* w1:評量優先順序/作業成績? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC3F /* w1:評量優先順序/上課表現? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC3G /* w1:評量優先順序/學習態度? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W1CTC3H /* w1:評量優先順序/進步情況? */
      1 = '優先考慮'  
      2 = '次要'  
      3 = '再其次'  
      4 = '不考慮'  
      97 = '不合理值'  
      99 = '未填答' ;

DATA library.&dataset ;
INFILE datafile LRECL=96;
INPUT
   STUD_ID  1-5             W1STWT1  6-24            W1CTC01  25           
   W1CTC02  26              W1CTC03  27-28           W1CTC04  29-30        
   W1CTC05  31-32           W1CTC06  33-34           W1CTC07  35           
   W1CTC08  36              W1CTC09  37              W1CTC10  38-39        
   W1CTC11  40-41           W1CTC12  42-43           W1CTC13  44-45        
   W1CTC14  46-47           W1CTC15  48-49           W1CTC16  50-51        
   W1CTC17  52-53           W1CTC18A  54-55          W1CTC19A  56-57       
   W1CTC20  58-59           W1CTC21A  60             W1CTC22  61-62        
   W1CTC23  63-64           W1CTC24  65-66           W1CTC25  67-68        
   W1CTC26  69-70           W1CTC27  71-72           W1CTC28  73-74        
   W1CTC29  75-76           W1CTC30  77-78           W1CTC31  79-80        
   W1CTC32  81-82           W1CTC33  83-84           W1CTC34  85-86        
   W1CTC35  87-88           W1CTC36  89-90           W1CTC37  91-92        
   W1SUMERR  93             W1SUMMIS  94-95          W1SUMTRP  96          
 ;                       

LABEL
   STUD_ID = "學生代碼"
   W1STWT1 = "w1:學生樣本權數(標準化過後)"
   W1CTC01 = "w1:任教的主要科目"
   W1CTC02 = "w1:主/副修/任教主要科目?"
   W1CTC03 = "w1:該科?幾年?"
   W1CTC04 = "w1:每週/這班/上課時數?"
   W1CTC05 = "w1:任教科目/這班程度？"
   W1CTC06 = "w1:任教科目/分組教學？"
   W1CTC07 = "w1:教學法/輸入式"
   W1CTC08 = "w1:教學法/探索或啟發式"
   W1CTC09 = "w1:教材/教科書"
   W1CTC10 = "w1:教材/課外參考書"
   W1CTC11 = "w1:教材/自行編寫或設計"
   W1CTC12 = "w1:教材/其他"
   W1CTC13 = "w1:輔助教具/視聽或電腦設備"
   W1CTC14 = "w1:輔助教具/掛圖/布偶/遊戲/益智玩具"
   W1CTC15 = "w1:輔助教具/戶外教學或參觀"
   W1CTC16 = "w1:上課/維持秩序"
   W1CTC17 = "w1:上課/測驗或考試"
   W1CTC18A = "w1:這班一週考幾次試？"
   W1CTC19A = "w1:每週/幾次作業？"
   W1CTC20 = "w1:做完指定作業時間？"
   W1CTC21A = "w1:作業/課本內習題"
   W1CTC22 = "w1:作業/參考書練習題"
   W1CTC23 = "w1:作業/課外讀物"
   W1CTC24 = "w1:作業/作文練習"
   W1CTC25 = "w1:作業/簡報、收集資料、寫心得"
   W1CTC26 = "w1:作業措施/公佈成績"
   W1CTC27 = "w1:作業措施/檢討答案"
   W1CTC28 = "w1:作業措施/獎賞表現好的"
   W1CTC29 = "w1:作業措施/處罰表現差的"
   W1CTC30 = "w1:作業措施/個別輔導"
   W1CTC31 = "w1:作業措施/通知家長"
   W1CTC32 = "w1:要求閱讀/心得報告?"
   W1CTC33 = "w1:評量優先順序/考試成績?"
   W1CTC34 = "w1:評量優先順序/作業成績?"
   W1CTC35 = "w1:評量優先順序/上課表現?"
   W1CTC36 = "w1:評量優先順序/學習態度?"
   W1CTC37 = "w1:評量優先順序/進步情況?"
   W1SUMERR = "w1:不合理值總和"
   W1SUMMIS = "w1:未填答總和"
   W1SUMTRP = "w1:劃記答案卡不應作答部分" ;

FORMAT
   W1CTC01 W1CTC0A.         W1CTC02 W1CTC0B.         W1CTC03 W1CTC0C.      
   W1CTC04 W1CTC0D.         W1CTC05 W1CTC0E.         W1CTC06 W1CTC0F.      
   W1CTC07 W1CTC0G.         W1CTC08 W1CTC0H.         W1CTC09 W1CTC0I.      
   W1CTC10 W1CTC1A.         W1CTC11 W1CTC1B.         W1CTC12 W1CTC1C.      
   W1CTC13 W1CTC1D.         W1CTC14 W1CTC1E.         W1CTC15 W1CTC1F.      
   W1CTC16 W1CTC1G.         W1CTC17 W1CTC1H.         W1CTC18A W1CTC18A.    
   W1CTC19A W1CTC19A.       W1CTC20 W1CTC2A.         W1CTC21A W1CTC21A.    
   W1CTC22 W1CTC2B.         W1CTC23 W1CTC2C.         W1CTC24 W1CTC2D.      
   W1CTC25 W1CTC2E.         W1CTC26 W1CTC2F.         W1CTC27 W1CTC2G.      
   W1CTC28 W1CTC2H.         W1CTC29 W1CTC2I.         W1CTC30 W1CTC3A.      
   W1CTC31 W1CTC3B.         W1CTC32 W1CTC3C.         W1CTC33 W1CTC3D.      
   W1CTC34 W1CTC3E.         W1CTC35 W1CTC3F.         W1CTC36 W1CTC3G.      
   W1CTC37 W1CTC3H.       ;
                     

LENGTH
   STUD_ID 4                W1CTC01 3                W1CTC02 3             
   W1CTC03 3                W1CTC04 3                W1CTC05 3             
   W1CTC06 3                W1CTC07 3                W1CTC08 3             
   W1CTC09 3                W1CTC10 3                W1CTC11 3             
   W1CTC12 3                W1CTC13 3                W1CTC14 3             
   W1CTC15 3                W1CTC16 3                W1CTC17 3             
   W1CTC18A 3               W1CTC19A 3               W1CTC20 3             
   W1CTC21A 3               W1CTC22 3                W1CTC23 3             
   W1CTC24 3                W1CTC25 3                W1CTC26 3             
   W1CTC27 3                W1CTC28 3                W1CTC29 3             
   W1CTC30 3                W1CTC31 3                W1CTC32 3             
   W1CTC33 3                W1CTC34 3                W1CTC35 3             
   W1CTC36 3                W1CTC37 3                W1SUMERR 3            
   W1SUMMIS 3               W1SUMTRP 3 ;

      

RUN ;
